version: '3'

services:
  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow:v2.11.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000

  prediction-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow-tracking-server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-server:5000
