version: '3'
services:
  mlflow-tracking-server:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    command: mlflow server --host 0.0.0.0 --port 5000
    restart: unless-stopped

  prediction-service:
    build:
      context: ./prediction-service
      dockerfile: ../prediction.Dockerfile
    container_name: prediction-service
    ports:
      - "8080:8080"
    depends_on:
      mlflow-tracking-server:
        condition: service_healthy
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-tracking-server:5000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
