name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure conda before environment setup
      - name: Configure Conda
        shell: bash -l {0}
        run: |
          conda config --add channels defaults
          conda config --set channel_priority strict

      # Environment Setup
      - name: Set up Python Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: prediction-service-env
          environment-file: prediction-service/conda.yaml
          auto-activate-base: false
          channels: defaults,conda-forge

      # Testing Phase
      - name: Run Python Tests
        shell: bash -l {0}
        working-directory: ./
        run: |
          conda activate prediction-service-env || exit 1
          pip install fastapi uvicorn httpx pytest pytest-cov || exit 1
          pytest tests/ --cov=prediction-service/src --cov-report=xml

      # Docker Setup and Build with proper path verification
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        working-directory: ./prediction-service  # Ensure we're in the right directory
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/prediction-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/prediction-service:latest

      - name: Cleanup
        if: always()
        run: docker system prune -f