name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Python Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: prediction-service-env
          environment-file: ./prediction-service/conda.yaml
          auto-activate-base: false

      - name: Run Python Tests
        shell: bash -l {0}
        working-directory: ./prediction-service
        run: |
          conda activate prediction-service-env
          pytest tests/ --cov=src --cov-report=xml
        if: success()

      - name: Build with Maven
        working-directory: ./prediction-service
        run: |
          mvn -B clean verify
        continue-on-error: false

      - name: Run Tests
        working-directory: ./prediction-service
        run: |
          mvn test
        if: success()

      - name: Build Docker Image
        working-directory: ./prediction-service
        run: |
          docker build . --file Dockerfile --tag prediction-service:latest
        timeout-minutes: 10
        if: success()

      - name: Test Docker Image
        run: |
          docker run -d --name prediction-service prediction-service:latest
          sleep 10
          docker ps | grep prediction-service || exit 1
        timeout-minutes: 5
        if: success()

      - name: Cleanup
        if: always()
        run: |
          docker rm -f prediction-service || true