name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start services
        run: docker compose up -d

      - name: Set up Python Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: prediction-service-env
          environment-file: ./prediction-service/conda.yaml
          auto-activate-base: false

      - name: Run Tests
        shell: bash -l {0}
        working-directory: ./prediction-service
        run: |
          conda activate prediction-service-env
          pytest tests/ --cov=src --cov-report=xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        working-directory: ./prediction-service
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/prediction-service:latest
          docker push ghcr.io/${{ github.repository }}/prediction-service:latest
        timeout-minutes: 10

      - name: Cleanup
        if: always()
        run: |
          docker compose down