name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Obter repositório
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Debug Build Output
        run: ls -l ./prediction-service/target

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Iniciar serviços
        run: docker compose up -d

      - name: Criar ambiente para executar testes com o conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda.yaml
          activate-environment: oml-env

      - name: Executar testes
        run: conda run --no-capture-output -n oml-env pytest

      - name: Iniciar sessão no repositório do GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/paulofcamara/prediction-service:latest