name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: |
        cd prediction-service
        mvn clean package -DskipTests
        ls -la target/
    
    - name: Debug directory contents
      run: |
        pwd
        ls -R prediction-service/target/
    
    - name: Build and push Docker images
      run: |
        cd ..
        docker compose build